# Generated by Django 4.0.6 on 2022-07-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_uploadimage_booking_p_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
